[colors.cursor]
cursor = "#fbf1c7"
text = "#fe8019"

[colors.normal]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#ff00ff"
magenta = "#d3896b"
red = "#fb4934"
white = "#928374"
yellow = "#fadb2f"

[colors.primary]
background = "#32302f"
foreground = "#d4ae3d"

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "Transparent"
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
